### ISSUE TITLE
When I open Phira, the screen remains black

### ISSUE THREAD

**Issue by corona-32** [TeamFlos/phira#405] opened 2024-09-07 08:30 UTC
I launch Phira(v0.6.4) on a Pixel 9 Pro XL with Android 14, 15 beta, or 15 QPR 1.1 beta, nothing is displayed.

Environment 
Device : Pixel9ProXL
OS version : Android14(AD1A.240530.030)
　　　　　  Android15(AP41.240726.010)

This document was translated from Japanese to English using Google Translate, so it may sound strange, but please forgive me.

**Comment by NuanRMxi** [comment] 2024-09-07 08:36
Duplicate of #391

**Closed** 2024-09-07 08:36 UTC
Labels: duplicate
