### ISSUE TITLE
[Bug?]only 1 finger work in phira windows

### ISSUE THREAD

**Issue by Palmtinkcc** [TeamFlos/phira#449] opened 2024-12-06 13:17 UTC
Phira Windows cannot handle multi-touch or multiple simultaneous inputs, and I don't know why. I’ve tried adjusting it to fullscreen mode, but that didn’t help. The game seems to only track a single mouse position, which prevents me from pressing multiple inputs simultaneously—even when playing on a Windows tablet.

This issue also occurs with long notes because I cannot press and hold them. From debugging, I found that the input detection only triggers when I click and release the mouse. If I don't release the mouse button, it doesn't detect anything.

I’ve tried looking through the various files, but I lack the expertise to fix this.

![Screenshot_3](https://github.com/user-attachments/assets/f38e1cc2-6ba7-4288-93ce-8e4d5bf7559e)

**Comment by YuevUwU** [comment] 2024-12-12 17:09
good duplicate of #173 
still thanks for describing details
although I think windows ver bugfix priority may not be very high...

**Closed** 2024-12-13 17:25 UTC
Labels: duplicate
